### ISSUE TITLE
Node.js v16 compatibility / unable to install via npm

### ISSUE THREAD

**Issue by remixer-dec** [edgarogh/quietjs-bundle#7]
Command failed
npm ERR! command sh -c run-s bundle
npm ERR! > quietjs-bundle@0.1.1 bundle
npm ERR! > node bundler.mjs
npm ERR! 
npm ERR! quietjs-bundle Downloading requirements...
npm ERR! file:///[...]/node_modules/quietjs-bundle/bundler.mjs:24
npm ERR!         process.stdout.clearLine();
npm ERR! 
npm ERR! TypeError: process.stdout.clearLine is not a function

**Comment by edgarogh** [comment]
I'll look at it, thank you for the report :heart:

**Comment by edgarogh** [comment]
Here you go : [`quietjs-bundle@0.1.2`](https://www.npmjs.com/package/quietjs-bundle/v/0.1.2) (commit 25baee4d96a29f27e2ba87ce7238e4c1a745fa53)
Have a great day !

**Comment by remixer-dec** [comment]
Thanks! 🐶
